### ISSUE TITLE
Doc update

### ISSUE THREAD

**Issue by jonny7737** [xNykram/youtube_search2#2]
Your examples need a little update the import should be:
from ytsearch import YTSearch

Using URL
from youtube_search2 import YoutubeSearch

Using keyword
from youtube_search2 import YoutubeSearch

**Comment by xNykram** [comment]
Hello @jonny7737,

Thanks for catching this one.

If you have any ideas on what I could add/improve, let me know. I was thinking of resolving some issues from https://github.com/joetats/youtube_search/issues.

**Comment by jonny7737** [comment]
My use case is covered for the moment but I will review the issues  in the other repo and see if anything might be useful in the future.

**Comment by xNykram** [comment]
https://github.com/xNykram/youtube_search2/releases/tag/v2.1.7
